user frappe;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 768;
}

http {
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    client_max_body_size 50m;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml text/javascript application/json application/javascript application/xml+rss application/rss+xml font/truetype font/opentype application/vnd.ms-fontobject image/svg+xml;

    upstream frappe-server {
        server 127.0.0.1:8000 fail_timeout=0;
    }

    upstream socketio-server {
        server 127.0.0.1:9000 fail_timeout=0;
    }

    server {
        listen 80;
        server_name _;

        root /home/frappe/frappe-bench/sites;

        location /assets {
            try_files $uri =404;
        }

        location ~ ^/protected/(.*) {
            internal;
            try_files /sites/$host/$1 =404;
        }

        location /socket.io {
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Frappe-Site-Name $host;
            proxy_set_header Origin $scheme://$http_host;
            proxy_set_header Host $host;

            proxy_pass http://socketio-server;
        }

        location / {
            rewrite ^(.+)/$ $1 permanent;
            rewrite ^(.+)/index\.html$ $1 permanent;
            rewrite ^(.+)\.html$ $1 permanent;

            location ~ ^/files/.*.(htm|html|svg|xml) {
                add_header Content-disposition "attachment";
                try_files /sites/$host/public/$uri @webserver;
            }

            try_files /sites/$host/public/$uri @webserver;
        }

        location @webserver {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Frappe-Site-Name $host;
            proxy_set_header Host $host;
            proxy_set_header X-Use-X-Accel-Redirect True;
            proxy_read_timeout 120;
            proxy_redirect off;

            proxy_pass http://frappe-server;
        }
    }
}
